CONTIKI_PROJECT = energy_sec client-node server-node
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..

include $(CONTIKI)/Makefile.dir-variables
MODULES += $(CONTIKI_NG_SERVICES_DIR)/simple-energest

include $(CONTIKI)/Makefile.include